### ISSUE TITLE
Website (ocular-gatsby) bug list

### ISSUE THREAD

**Issue by xintongxia** [uber-web/loaders.gl#194]
Not yet deployed
- [x] deck.gl based examples don't resize properly P1
- [x] project dropdown doesn't work properly P1

Deployed
- [x] Get started link is wrong #261 P1
- [x] Layout is broken if accessing doc page directly from URL (e.g. https://docs/contributing)  P0
- [x] Topbar Github link is broken P1
- [x] loaders.gl dropdown doesn't work P2

**Comment by tgorkin** [comment]
I've spent some time looking into "Layout is broken if accessing doc page directly from URL (e.g. https://docs/contributing) P0".  I think I've identified some more specific symptoms, but am stuck on actual root cause or how to fix.  Putting the results of my debugging here in case it helps:

1.  This issue only occurs on production builds.  To repro locally, you'll need to run `yarn build && yarn serve`.  The issue doesn't occur when running `yarn develop`.
2.  To repro, you need to load http://localhost:9000/docs directly.  If you first load http://localhost:9000/ and then browse to Documentation, the layout is fine.
2. Comparing the html of the page between the two situations, the bad layout has an extra `<div class="markdown-body">` wrapping the bulk of the content of the page.  This leads me to https://github.com/uber-web/ocular/blob/master/modules/gatsby/src/templates/doc-n.jsx, but I don't understand ocular-gatsby's templates or static build system enough to to debug through the layers of indirection.
3. I think I've confirmed through breakpoints and console logs that the correct branching logic is being executed in https://github.com/uber-web/ocular/blob/master/modules/gatsby/src/components/layout/top-level-layout.jsx, but I'm not 100% confident in my debugging since this is a static build-only issue.

**Comment by jckr** [comment]
the page renders different HTML depending on whether we access it through a url or following links from the home page (ie https://loaders.gl/arrowjs/ then documentation then one specific page). 

If following links from the home page, the HTML has a BodyGrid styled component that it doesn't have when accessing page through a url.

**Comment by jckr** [comment]
so. The BodyGrid styled component is used in the built version, but for some reason it renders a <div class="markdown-body"> instead of <div class="styled__BodyGrid-sc-1bsyyd-2 bODEnQ">. 

I am now suspecting that some process goes through the rendered code, selects this class and replaces its classname by markdown-body.

**Comment by jckr** [comment]
![image](https://user-images.githubusercontent.com/9727630/57420863-52e56100-71be-11e9-8fcc-576021278375.png)
it's not stupid if it works: I can mitigate the problem by adding a (useless) div around the bodygrid. 

will cut a new ocular version now.

**Comment by ibgreen** [comment]
Looks like get started link is still broken, updated list.
