### ISSUE TITLE
Cesium viewer and loader.gl integration

### ISSUE THREAD

**Issue by xintongxia** [uber-web/loaders.gl#481]
Use `loaders.gl` loading and parsing functionalities, traverse tiles and feed parsed tile data to Cesium viewer.

**Comment by OmarShehata** [comment]
An initial version of this is functional in https://github.com/uber-web/loaders.gl/pull/502. Here were some of the things I ran into that I think would make it even easier to use Loaders.gl without relying on any of CesiumJS's built-in traversal:

* [ ] Add an `onTileVisible` event, that returns the tile header and whether its state was changed to visible or not visible. This is needed both when zooming out so that the high LODs can be hidden (for performance reasons) as well as when loading a tileset with replacement refinement. Otherwise the root tile will poke through the higher res child tiles.
* [ ] Do not fire `onTileLoad` event for tiles that point to external tilesets. Since it seems like Loaders.gl will automatically handle loading those tilesets, it's just something we have to check for and ignore when adding tiles to the scene.

**Comment by OmarShehata** [comment]
I actually wasn't aware `tileset3d.update` provided a list of visible tiles. I could probably just use that. I just expected it would be there because of the other tile events (and because CesiumJS has that event) but I don't think it's too hard to integrate with that instead.

 > Your comment "this is needed when zooming out" makes me suspect we have a more general bug

This is what I was suspecting as well, although I'm curious why this bug does not appear in the Deck.gl examples. If the parent tile is just set to be hidden instead of unloaded then that could be why.
